### ISSUE TITLE
Tetranomicon v1.5.3 for Minecraft 1.18.2 can't open single player world: Invalid player data

### ISSUE THREAD

**Issue by Snowball0409** [Syrikal/Tetranomicon#26]
I am playing the custom modpack for minecraft 1.18.2, after I update tetranomicon from 1.4 to 1.5, I can't open any existed world or new world, it will report the error **"Invalid player data"**, and can see the logs like below:
``` 
[Server thread/ERROR]: Couldn't place player in world
io.netty.handler.codec.EncoderException: String too big (was 38769 bytes encoded, max 32767)
	at net.minecraft.network.FriendlyByteBuf.m_130072_(FriendlyByteBuf.java:509) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_130070_(FriendlyByteBuf.java:503) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at se.mickelus.mutil.data.AbstractUpdateDataPacket.lambda$toBytes$1(AbstractUpdateDataPacket.java:36) ~[mutil-1.18.2-4.5.0.jar%23192!/:4.5.0]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at se.mickelus.mutil.data.AbstractUpdateDataPacket.toBytes(AbstractUpdateDataPacket.java:34) ~[mutil-1.18.2-4.5.0.jar%23192!/:4.5.0]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:77) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:90) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:121) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.sendTo(SimpleChannel.java:101) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at se.mickelus.mutil.network.PacketHandler.sendTo(PacketHandler.java:91) ~[mutil-1.18.2-4.5.0.jar%23192!/:4.5.0]
	at se.mickelus.tetra.data.DataManager.sendToPlayer(DataManager.java:176) ~[tetra-1.18.2-4.10.1.jar%23245!/:4.10.1]
	at se.mickelus.mutil.data.DataStore.sendToPlayer(DataStore.java:112) ~[mutil-1.18.2-4.5.0.jar%23192!/:4.5.0]
	at se.mickelus.tetra.data.DataManager.playerConnected(DataManager.java:141) ~[tetra-1.18.2-4.10.1.jar%23245!/:4.10.1]
	at net.minecraftforge.eventbus.ASMEventHandler_972_DataManager_playerConnected_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833) ~[forge-1.18.2-40.2.4-universal.jar%23274!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:238) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23269!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

You can see the modlist in this link: https://www.curseforge.com/minecraft/modpacks/tetra-plus-1-18-2
I hope it can be fixed, thanks!

**Comment by Proxwian** [comment]
Bump

**Comment by Syrikal** [comment]
Can you try this with Tetra, Tetranomicon, and _no other Tetra expansions?_ I've discovered that there's a limit to how much extra Tetra stuff can be added at once. Tetranomicon's small enough to fit, but if you had a bunch of other Tetra compatibility patches then you might run over the limit.

**Comment by Snowball0409** [comment]
If no other expansions, it looks like work well. Maybe I use my own datapack cause it? But it also work well after I add lots of new materials or schematics in datapack. Is there any way to fix it except remove other expansion or datapack?

**Comment by Syrikal** [comment]
Tetranomicon has a _lot_ of content. I'd suggest cracking open the jar, getting the data out, and removing stuff you don't need - most files start with the mod ID of the mod that they're made for - before making a datapack out of what's left. Other than that, I'd suggest taking the issue up with Tetra. Nothing I can do about it, unfortunately.
